services:
  - type: web  # Indica que é um serviço web
    name: flask-app  # Nome da aplicação
    env: python  # Ambiente para rodar a aplicação (Python)
    buildCommand: "pip install -r requirements.txt"  # Comando para instalar as dependências
    startCommand: "python app.py"  # Comando para iniciar a aplicação
    port: 5000  # Porta que o Render irá expor para o tráfego
